# Generated by Django 6.0.6 on 2026-06-14 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='reading_time',
        ),
    ]
